# Generated by Django 5.2.8 on 2025-12-01 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customorder',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shoporder',
            old_name='address',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shoporder',
            old_name='total_amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='customorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop-orders/'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='wearName',
            field=models.CharField(default='Unnamed Wear', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='custom-orders/'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ShopOrderItem',
        ),
    ]
