# Generated by Django 5.2.8 on 2025-12-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_details_customorder_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
